TeachMyChild/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeachMyChild.Core.Implementations;
using TeachMyChild.Data;
using TeachMyChild.Data.Contracts;
using TeachMyChild.Helpers;
using TeachMyChild.Logic.Contracts;

namespace TeachMyChild.Controllers
{
    [Authorize(Roles = AppConstants.ADMIN_ROLE_NAME)]
    public class CoursesController : Controller
    {
        IUnitOfWork uow;
        ICourseService courseService;
        ICourseCategoryService courseCatService;
        public CoursesController(IUnitOfWork _uow, ICourseService _courseService, ICourseCategoryService _courseCatService)
        {
            uow = _uow;
            courseService = _courseService;
            courseCatService = _courseCatService;
        }
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Courses
        [AllowAnonymous]
        public ActionResult Index()
        {
            var alCourses = courseService.GetAll();
            return View(alCourses);
        }

        // GET: Courses/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = courseService.GetById(id.Value);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = courseCatService.GetAll().AsQueryable().Select(c => new SelectListItem { Text = c.Name, Value = c.ID.ToString() });
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Course course, string CategoryId)
        {
            ViewBag.CategoryId = courseCatService.GetAll().AsQueryable().Select(c => new SelectListItem { Text = c.Name, Value = c.ID.ToString() });
            if (ModelState.IsValid)
            {
                try
                {

                    if (courseService.CourseWithNameAlreadyExists(course.Name, course.CategoryId))
                    {
                        ModelState.AddModelError("", "A course with this name already exists under the selected category");
                        return View(course);
                    }
                    courseService.Save(course);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // Todo: Log ex
                    ModelState.AddModelError("", "An error occured while saving the course");
                    return View(course);
                }
            }            
            return View(course);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,DateCreated,DateModified")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Categories()
        {
            var categories = courseCatService.GetAll();
            return View(categories);
        }
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCategory(CourseCategory model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    courseCatService.CreateNewCategory(model);
                    return RedirectToAction("Categories");
                }
                catch (Exception ex)
                {
                    // Log ex
                    ModelState.AddModelError("", "An error occured while saving category");
                    return View();
                }
            }
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TeachMyChild/Controllers/TutorController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TeachMyChild.Core.Implementations;
using TeachMyChild.Data.Contracts;
using TeachMyChild.Helpers;
using TeachMyChild.Logic.Contracts;
using TeachMyChild.Logic.Contracts.Utility;
using TeachMyChild.Utilities;
using TeachMyChild.ViewModels;

namespace TeachMyChild.Controllers
{
    [Authorize]
    public class TutorController : BaseController
    {
        private ITutorProfileService tutorProfileService;
        private IAccountService actService;
        private IEducationEntityService eduService;
        private IWorkExperienceEntityService workExperienceEntityService;
        private ICourseService courseService;
        private ICourseCategoryService courseCategoryService;
        private IChatService chatService;
        IFileService fileService;
        IUnitOfWork uow;
        ApplicationUserManager userManager;
        public TutorController(ApplicationUserManager _userManager, ITutorProfileService _tutorProfileService, IAccountService _actService, IEducationEntityService _eduService,
            IWorkExperienceEntityService _workExperienceEntityService, ICourseService _courseservice, ICourseCategoryService _courseCategoryService, IChatService _chatService,
        IFileService _fileService, IUnitOfWork _uow)
        {
            uow = _uow;
            tutorProfileService = _tutorProfileService;
            actService = _actService;
            eduService = _eduService;
            workExperienceEntityService = _workExperienceEntityService;
            courseService = _courseservice;
            courseCategoryService = _courseCategoryService;
            chatService = _chatService;
            fileService = _fileService;
            userManager = _userManager;
        }
        [AllowAnonymous]
        // GET: Tutor
        public ActionResult Index()
        {
            ViewBag.DefaultTutorProfileImgUri = AppConstants.DEFAULT_TUTOR_PROFILE_IMAGE_URI;
            var allTutors = tutorProfileService.GetAllTutors(); // Todo: Get only completed profiles, not all profiles
            return View(allTutors);
        }

        // GET: Tutor/Create
        public ActionResult Create(string id)
        {
            return RedirectToAction("Step1", new { id = id });
            
        }


        // POST: Tutor/Create
      
        [HttpPost]
        public ActionResult Create(AddTutorViewModel model)
        {
            return View();      
        }

     
        public async Task<ActionResult> Step1(/*string id*/)
        {
            var user = await GetLoggedInUserAccount();
            if (!user.IsAccountComplete)
            {
                var nigeriaStates = P.GetStates("nigeria");
                ViewBag.States = nigeriaStates.AsEnumerable().Select(i => new SelectListItem { Text = i, Value = i });

                var userProfile = uow.tutorProfileDao.GetByUserAccountId(user.Id);
                ProfileBasics tutorModel = null;
                bool isEditing = true;
                if (userProfile == null)
                {
                    isEditing = false;
                    tutorModel = new ProfileBasics
                    {
                        AccountID = user.Id,
                        LastName = user.LastName,
                        FirstName = user.FirstName,                        
                        DateOfBirth = new DateTime(1985, 5, 5)    // just a default date to avoid error
                    };
                }
                else
                {
                    tutorModel = Mapper.Map<TutorProfile, ProfileBasics>(userProfile);
                    tutorModel.AccountID = user.Id;
                    tutorModel.ProfileID = userProfile.ID;
                }
                tutorModel.IsEditing = isEditing;

                ViewBag.AccountId = user.Id;
                return View(tutorModel);
            }
            // Account already complete, go to dashboard
            return RedirectToAction("Dashboard", new { id = user.Id });
        }

        // POST: Tutor/Create
        [HttpPost]
        public ActionResult Step1(ProfileBasics model)
        {
            var nigeriaStates = P.GetStates("nigeria");
            ViewBag.States = nigeriaStates.AsEnumerable().Select(i => new SelectListItem { Text = i, Value = i });
            if (!ModelState.IsValid)
            {
                // Todo: validate DateOfBirth from client side perhaps through Jquery
                ModelState.AddModelError("", "One or more fields has a wrong input");
                return View(model);
            }

            try
            {
                string userAccountId = model.AccountID;
                if (String.IsNullOrEmpty(userAccountId))
                {
                    ViewBag.ErrorMsg = "Unable to retrieve user account";
                    return View(model);
                }
                var userAct = actService.GetAccountById(userAccountId);
                if (userAct == null)
                {
                    ViewBag.ErrorMsg = "User account cannot be null";
                    return View(model);
                }
                
                if (model.IsEditing)
                {
                    var tutorModel = uow.tutorProfileDao.Get(model.ProfileID);
                    Mapper.Map(model, tutorModel);  // https://stackoverflow.com/a/25242322/7162741 suggested the fix for https://stackoverflow.com/questions/23201907/asp-net-mvc-attaching-an-entity-of-type-modelname-failed-because-another-ent caused by  // tutorModel = Mapper.Map<ProfileBasics, TutorProfile>(model);
                    tutorModel.LastStepCompleted = 1;
                    tutorProfileService.Update(tutorModel);
                }
                else
                {
                    var tutorModel = Mapper.Map<ProfileBasics, TutorProfile>(model);
                    tutorModel.Account = userAct;
                    tutorModel.LastStepCompleted = tutorModel.LastStepCompleted > 1 ? tutorModel.LastStepCompleted : 1;
                    tutorProfileService.Save(tutorModel, userAct);
                }
                return RedirectToAction("Step2", new { id = userAccountId });
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMsg = "An error occured while saving user records" + ex.ToString();
                // Todo: log error
                return View();
            }
        }
        public async Task<ActionResult> Step2()
        {
            // in case someone trie to just step 1, first check if step 1 is completed, if not, redirect user to page 1.
            // do same for other steps as well
            var userAccount = await GetLoggedInUserAccount(); // userManager.FindByNameAsync(loggedInUsername);

            if (!userAccount.IsAccountComplete)
            {
                var userProfile = uow.tutorProfileDao.GetByUserAccountId(userAccount.Id);
                if (userProfile.LastStepCompleted < 1)
                    return RedirectToAction("Step1");   // must complete step 1 first
                EduAndProfessionalBackground tutorModel = null;
                bool isEditing = true;
                if (userProfile == null)
                {
                    tutorModel = new EduAndProfessionalBackground
                    {
                        AccountID = userAccount.Id,
                        Educations = new List<Education>(),
                        WorkExperiences = new List<WorkExperience>()
                    };
                }
                else
                {
                    tutorModel = Mapper.Map<TutorProfile, EduAndProfessionalBackground>(userProfile);

                    tutorModel.AccountID = userAccount.Id;
                    tutorModel.ProfileId = userProfile.ID;
                }
                tutorModel.IsEditing = isEditing;

                ViewBag.AccountId = userAccount.Id;
                return View(tutorModel);
            }
            return RedirectToAction("MyDashBoard");
            //return RedirectToAction("Login", "Account", new { msg = "Your profile setup is complete, you can now login" });
        }
        [HttpPost]
        public ActionResult Step2(EduAndProfessionalBackground model, string action)
        {
            if (ModelState.IsValid)
            {
                // For us to have reached step2, a tutor profile must have been created
                var profile = uow.tutorProfileDao.Get(model.ProfileId);
                if (profile == null)
                {
                    ModelState.AddModelError("", "user profile could not be found");
                    // Todo: log this
                    return View(model);
                }
                if (!model.Educations.Any())
                {
                    ModelState.AddModelError("", "Please add some education details");
                    // Todo: log this
                    return View(model);
                }

                // get the education and work experiences from the incoming model
                var newEdus = new List<EducationEntity>();
                foreach (var edu in model.Educations)
                {
                    newEdus.Add(new EducationEntity { InstitutionName = edu.InstitutionName, Concentration = edu.Concentration, DegreeAwarded = edu.DegreeAwarded, StartDate = edu.StartDate, EndDate = edu.EndDate, StillStudiesHere = edu.StillStudiesHere });
                }
                var newExperiences = new List<WorkExperienceEntity>();
                foreach (var exp in model.WorkExperiences)
                {
                    newExperiences.Add(new WorkExperienceEntity { CompanyName = exp.CompanyName, Description = exp.Description, JobTitle = exp.JobTitle, StartDate = exp.StartDate, EndDate = exp.EndDate, StillWorksHere = exp.StillWorksHere });
                }

TeachMyChild/Views/Courses/AddCategory.cshtml
@model TeachMyChild.Core.Implementations.CourseCategory

@{
    ViewBag.Title = "AddCategory";
}

<h2>AddCategory</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CourseCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
 

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TeachMyChild/Views/Courses/Categories.cshtml
@model IEnumerable<TeachMyChild.Core.Implementations.CourseCategory>

@{
    ViewBag.Title = "Categories";
}

<h2>Categories</h2>

<p>
    @Html.ActionLink("Create New", "AddCategory")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateModified)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateModified)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditCategory", new { id=item.ID }) |
            @Html.ActionLink("Details", "CategoryDetails", new { id=item.ID }) |
            @Html.ActionLink("Delete", "DeleteCategory", new { id=item.ID })
        </td>
    </tr>
}

</table>

TeachMyChild/Views/Courses/Create.cshtml
@model TeachMyChild.Core.Implementations.Course

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Display Image")
            <div class="col-md-10">
                @Html.TextBox("file", "", new { type = "file", @class = "form-control", @accept = ".jpg,.jpeg,.png" })                
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId")
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TeachMyChild/Views/Courses/Delete.cshtml
@model TeachMyChild.Core.Implementations.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TeachMyChild/Views/Courses/Details.cshtml
@model TeachMyChild.Core.Implementations.Course

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TeachMyChild/Views/Courses/Edit.cshtml
@model TeachMyChild.Core.Implementations.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TeachMyChild/Views/Courses/Index.cshtml
@model IEnumerable<TeachMyChild.Core.Implementations.Course>

@{
    ViewBag.Title = "Index";
}



<section class="mainContent full-width clearfix">
    <div class="container">
       
        <h3>Available Course</h3>
        <div class="row">
            <div class="col-xs-12">
                @foreach (var item in Model)
                {
                    <div class="media courseList couresListPage" style="padding-top:5px; padding-bottom:5px">
                        <a class="media-left border-color-1" href="#" style="margin-top: 15px">
                             
                            @{
                                if (item.ImageUri == null)
                                {
                                    <img class="media-object" src="~/assets/img/course-1.jpg" alt="Image">
                                }
                                else
                                {
                                    <img class="media-object" src=@Html.Raw(item.ImageUri.TrimStart('~').Replace(" ","%20")) alt="Image">
                                }
                            }
                         
                        @*    <span class="sticker bg-color-1" style="margin-bottom:20px">&#8358;50 <h5 style="margin-left:5px; color: white"><b>/hr.</b></h5></span>*@

                        </a>
                        <div class="media-body" style="padding-left:10px">
                            <h3 class="media-heading"><a href="#" class="color-1">@Html.DisplayFor(modelItem => item.Description)</a></h3>
                            <p>@Html.DisplayFor(modelItem => item.Name)</p> 
                            <ul class="list-inline btn-yellow btnPart">
                                <li><a href='@Url.Action("Index", "Tutor")' class="btn btn-primary "> <i class="fa fa-pencil-square-o " aria-hidden="true"></i>Browse tutors</a></li>
                                @*<li><a href="course-single-left-sidebar.html" class="btn btn-link"><i class="fa fa-angle-double-right" aria-hidden="true"></i> More</a></li>*@
                            </ul>
                            <div class="btn btn-primary" style="margin-top:20px;">
                                <h4 style="padding:0px; color:white; margin:0 auto">&#8358;50 per Hour</h4>
                            </div>
                        
                        </div>
                    </div>
                }
              </div>
        </div>

        @*<div>
            <li style="list-style-type: none;"><a href="cart-page.html" class="btn btn-primary "><i class="fa fa-pencil-square-o " aria-hidden="true"></i>Browse Tutors</a></li>

        </div>*@

        <div class="pagerArea text-center">
            <ul class="pager">
                <li class="prev"><a href="#"><i class="fa fa-arrow-left" aria-hidden="true"></i>Prev</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">...</a></li>
                <li><a href="#">15</a></li>
                <li class="next"><a href="#">Next<i class="fa fa-arrow-right" aria-hidden="true"></i></a></li>
            </ul>
        </div>

    </div>

    @*<div class="container">
        <h3>available Course</h3>
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateCreated)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateModified)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateCreated)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateModified)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

        </table>
        </div>*@
</section>