TeachMyChild/Controllers/ParentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeachMyChild.Helpers;
using TeachMyChild.Logic.Contracts;

namespace TeachMyChild.Controllers
{
    [Authorize(Roles ="Parent")]
    public class ParentController : BaseController
    {
        IAccountService actService;
        public ParentController(IAccountService _actService)
        {
            actService = _actService;
        }
        // GET: Parent
        public ActionResult Index()
        {
            return View();
        }

        // GET: Parent/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Parent/Create
        public ActionResult Create(string id)
        {
            var user = actService.GetAccountById(id);
            if(user == null)
            {
                TempData[KeyRings.ERROR_MESSAGE] = "Your account does not exist";
                return RedirectToAction("Error");
            }
            if (user.IsAccountComplete)
            {
                TempData[KeyRings.ERROR_MESSAGE] = "Your profile is complete, please login to your account";
                return RedirectToAction("Error");
            }
            return View();
        }

        // POST: Parent/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Dashboard()
        {
            return View();
        }

        // GET: Parent/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Parent/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Message()
        {
            return View();
        }
    }
}

TeachMyChild/Controllers/TutorialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TeachMyChild.Core.Implementations;
using TeachMyChild.Helpers;
using TeachMyChild.Logic.Contracts;
using TeachMyChild.Utilities;
using TeachMyChild.ViewModels;

namespace TeachMyChild.Controllers
{
    public class TutorialsController : BaseController
    {
        ApplicationUserManager userManager;
        ITutorialService tutorialService;
        ICourseService courseService;
        ITutorProfileService tutorProfileService;
        IParentProfileService parentProfileService;
        IBidService bidService;
        public TutorialsController(ApplicationUserManager _userManager, ITutorialService tutorialService, ICourseService _courseService, ITutorProfileService tutorProfileService, IParentProfileService parentProfileService, IBidService _bidService)
        {
            userManager = _userManager;
            this.tutorialService = tutorialService;
            this.tutorProfileService = tutorProfileService;
            this.parentProfileService = parentProfileService;
            bidService = _bidService;
            courseService = _courseService;
        }
        [Authorize]
        // GET: Tutorials
        public async Task<ActionResult> Index()
        {
            var tutorials = tutorialService.GetAll().OrderByDescending(t => t.DateCreated);
            //if(tutorials.Count() == 0)
            //{
            //    var testTutorials = new List<TutorialRequest>()
            //    {
            //        new TutorialRequest
            //        {
            //            ShortSummary = "I need a maths tutor for my children",
            //            Details = @"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio repellat,
            //                                veniam totam asperiores aut
            //                                aspernatur repudiandae, eos quia numquam cupiditate reiciendis dolore facere,
            //                                soluta est maiores harum
            //                                ullam earum culpa",
            //            City="Yaba",
            //            State = "Lagos", ProposedChargePerHour =1650, DateCreated = DateTime.Now, Course =new Course { Name="Chemistry"},//  Courses = new List<Course> {new Course { Name="Chemistry"}, new Course { Name= "Physics"} },
            //            Poster = GetLoggedInParentProfile()
            //        }
            //    };
            //    return View(testTutorials);
            //}
            return View(tutorials);
        }
        [Authorize(Roles = "Parent")]
        public ActionResult NewRequest()
        {
            var nigeriaStates = P.GetStates("nigeria");
            ViewBag.States = nigeriaStates.AsEnumerable().Select(i => new SelectListItem { Text = i, Value = i });
            var allCourses = courseService.GetAll();
            ViewBag.Courses = allCourses.AsEnumerable().Select(c => new SelectListItem { Text = c.Name, Value = c.ID.ToString() });

            //CreateNewTutorialRequestVM model = new CreateNewTutorialRequestVM
            //{
            //    CourseListItems = allCourses.Select(c => new SelectListItem { Text = c.Name, Value = c.ID.ToString() })
            //};
            return View();
        }

        [Authorize(Roles ="Parent")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> NewRequest(CreateNewTutorialRequestVM model, string CourseId)
        {
            var nigeriaStates = P.GetStates("nigeria");
            ViewBag.States = nigeriaStates.AsEnumerable().Select(i => new SelectListItem { Text = i, Value = i });
            var allCourses = courseService.GetAll();
            ViewBag.Courses = allCourses.AsEnumerable().Select(c => new SelectListItem { Text = c.Name, Value = c.ID.ToString() });
            if (String.IsNullOrEmpty(CourseId))
            {
                ModelState.AddModelError("", "Please select a course");
                return View(model);
            }
            //var loggedInUsername = User.Identity.Name;
            var user = await GetLoggedInUserAccount();//  userManager.FindByNameAsync(loggedInUsername);
            
            
            if (ModelState.IsValid)
            {
                try
                {
                    var chosenCourse = allCourses.Find(c => c.ID == int.Parse(CourseId));//  courseService.GetById(int.Parse(CourseId));
                    if (chosenCourse == null)
                    {
                        ModelState.AddModelError("", "Please select a course");
                        return View(model);
                    }
                    TutorialRequest tutorial = new TutorialRequest()
                    {
                        City = model.City,
                        ShortSummary = model.ShortSummary,
                        Details = model.Description,
                        NumberOfHoursInADay = model.NumberOfHoursInADay,
                        NumberOfDaysInAWeeek = model.NumberOfDaysInAWeeek,
                        NumberOfStudents = model.NumberOfStudents,
                        ProposedChargePerHour = model.ProposedChargePerHour,
                        Course = chosenCourse,
                        State = model.State,
                        Poster = GetLoggedInParentProfile(), 
                        
                    };
                    tutorialService.AddNewTutorialRequest(tutorial);
                    ViewBag.Msg = "You request has been posted";
                    return View();
                }
                catch (Exception ex)
                {
                    ViewBag.Msg = "An error occured while processing your request and we are currently investigating it.";
                    throw;
                }
       
               
            }
            return View();
        }

        [Authorize(Roles ="Tutor")]
        public ActionResult Bid()
        {
            return View();
        }

        [Authorize(Roles = "Tutor")]
        [HttpPost]
        public async Task<ActionResult> Bid(PlaceBidVM model)
        {
            // Todo: Validate the proposal amount (max and min vals) properly
            decimal bidAmount = 0;
            if(!decimal.TryParse(model.Amount, out bidAmount) || bidAmount < AppConstants.MINIMUM_HOURLY_RATE || bidAmount > AppConstants.MAXIMUM_HOURLY_RATE)
            {
                return Json(new { success = false, msg = "Invalid amount" });                
            }
            var theTutorialRequest = tutorialService.GetById(model.TutorialRequestId);
            if(theTutorialRequest == null)
                return Json(new { success = false, msg = "This tutorial request does not exist again" });            
            var theTutor = await GetLoggedInTutorProfile();
            if (bidService.BidAlreadySubmitted(theTutor.ID, theTutorialRequest.ID))
                return Json(new { success = false, msg = "You have already submitted a bid for this tutorial" });

            try
            {
                TutorialBid bid = new TutorialBid
                {
                    Amount = bidAmount,
                    Proposal = model.Proposal,
                    Bidder = theTutor,
                    Tutorial = theTutorialRequest
                };
                tutorialService.PlaceTutorialBid(bid);
                return Json(new { success = true, msg = "Bid successfully placed" });
            }
            catch (Exception ex)
            {
                // Todo: log ex
                return Json(new { success = false, msg = "An error occured while placing your bid" });
            }            
        }
        [Authorize(Roles = AppConstants.TUTOR_ROLE_NAME + "," + AppConstants.PARENT_ROLE_NAME)]
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var tutorialRequest = tutorialService.GetById(id.Value);
            if (tutorialRequest == null)
                return HttpNotFound();
            var user = await GetLoggedInUserAccount();
            if (await userManager.IsInRoleAsync(user.Id, AppConstants.TUTOR_ROLE_NAME))
                ViewBag.LoggedInUser = AppConstants.TUTOR_ROLE_NAME;
            return View(tutorialRequest);
        }

        private async Task<TutorProfile> GetLoggedInTutorProfile()
        {
            var username = User.Identity.Name;
            if (String.IsNullOrEmpty(username))
                return null;
            return tutorProfileService.GetProfileByUserAccountName(username);
        }
        private ParentProfile GetLoggedInParentProfile()
        {
            var username = User.Identity.Name;
            if (String.IsNullOrEmpty(username))
                return null;
            return parentProfileService.GetProfileByUserAccountName(username);
        }
        private async Task<ApplicationUser> GetLoggedInUserAccount()
        {
            return await userManager.FindByNameAsync(User.Identity.Name);
        }
    }
}

TeachMyChild/Views/Parent/Create.cshtml
@{
    ViewBag.Title = "Create";
}
<h1>Parent</h1>
<h2>Please complete your profile before you can login</h2>

TeachMyChild/Views/Parent/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}
<link href="~/assets/css/dashboard.css" rel="stylesheet" />

<section class="mainContent full-width clearfix"></section>

<section id="container">
    <!--header start-->
    <header class="header white-bg">
        <div class="sidebar-toggle-box" onclick="showNavBar()">
            <i class="fa fa-bars"></i>
        </div>

        <div class="nav notify-row" id="top_menu">
            <!--  notification start -->
            <ul class="nav top-menu">

                <!-- settings end -->
                <!-- inbox dropdown start-->
                <li id="header_inbox_bar" class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge badge-danger">5</span>
                    </a>

                </li>
                <!-- inbox dropdown end -->
                <!-- notification dropdown start-->
                <li id="header_notification_bar" class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="fa fa-bell-o"></i>
                        <span class="badge badge-warning">7</span>
                    </a>

                </li>

            </ul>

        </div>
        <div class="top-nav ">
            <!--search & user info start-->
            <ul class="nav pull-right top-menu">

                <!-- user login dropdown start-->
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <img alt="" src="~/assets/img/team-1.jpg">
                        <span class="username">John Doe</span>

                    </a>
                </li>
                <li class="toggle-right" onclick="showRightBar()">
                    <i class="fa  fa-bars "></i>
                </li>

            </ul>

        </div>
    </header>
    <!--header end-->
    <!--sidebar start-->
    <aside>
        <div id="sidebar" class="nav-collapse ">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">
                <li>
                    <a class="active" href="#">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-laptop"></i>
                        <span>Ongoing Tutorial</span>
                    </a>

                </li>

                <li class="sub-menu">
                    <a href=@Url.Action("Index","Tutorials")>
                        <i class="fa fa-book"></i>
                        <span>View Posted Requests</span>
                    </a>

                </li>

                <li class="sub-menu">
                    <a href=@Url.Action("NewRequest","Tutorials")>
                        <i class="fa fa-cogs"></i>
                        <span>Post New Requests</span>
                    </a>

                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-tasks"></i>
                        <span>Featured Tutorials</span>
                    </a>

                </li>

                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class=" fa fa-user"></i>
                        <span>Profile</span>
                    </a>

                </li>


            </ul>
            <!-- sidebar menu end-->
        </div>
    </aside>


    <div class="clearfix"></div>
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <!--state overview start-->
            <div class="row state-overview">
                <div class="col-sm-4">
                    <section class="tiles">
                        <div class="symbol terques">
                            <i class="fa fa-user"></i>
                        </div>
                        <div class="value">
                            <h1 class="counter">
                                29
                            </h1>
                            <p>Tutors</p>
                        </div>
                    </section>
                </div>
                <div class="col-sm-4 ">
                    <section class="tiles">
                        <div class="symbol red">
                            <i class="fa fa-book"></i>
                        </div>
                        <div class="value">
                            <h1 class="counter">
                                20
                            </h1>
                            <p>Subject</p>
                        </div>
                    </section>
                </div>
                <div class="col-sm-4">
                    <section class="tiles">
                        <div class="symbol yellow">
                            <i class="fa fa-sign-out"></i>
                        </div>
                        <div class="value">
                            <h1 class="counter">
                                17
                            </h1>
                            <p>Requests</p>
                        </div>
                    </section>
                </div>

            </div>
            <div class="col-sm-6">
                <canvas id="myChart" width="300" height="300"></canvas>

            </div>



        </section>
    </section>
    <!--main content end-->
    <!-- Right Slidebar start -->
    <div id="sidebar-right" class="nav-collapse ">
        <div class="favorite-tutors">

            <h4>favorite tutors</h4>
            <div class="tutor">
                <img src="~/assets/img/team-3.jpg" alt="">
                <div class="details">
                    <p>Jane Doe</p>
                    <p>Maths,English</p>
                </div>
            </div>
            <div class="tutor">
                <img src="~/assets/img/team-3.jpg" alt="">
                <div class="details">
                    <p>Jane Doe</p>
                    <p>Maths,English</p>
                </div>
            </div>

        </div>

        <div class="suggestions">
            <h4>suggestions</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio reprehenderit esse
                assumenda non, porro labore! Molestias quasi facilis, sed temporibus deleniti explicabo
                rerum facere optio perferendis dignissimos quos tempore exercitationem.
            </p>
        </div>
        <div class="reviews">
            <h4>reviews</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio reprehenderit esse
                assumenda non, porro labore! .
            </p>
            <p class="author">-- <span>Jane Doe</span> </p>
        </div>

    </div>
    <!-- Right Slidebar end -->


</section>





<style>
    .checked {
        color: orange;
    }
</style>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script src="~/assets/js/dashboard.js"></script>














@*<section class="mainContent full-width clearfix">
    <div class="container">
        <div class="row">
            <h2>Dashboard</h2>
            <div>
                Notification, message and Bids tabs
            </div>
            <div class="row">
                <label>Full name</label>
                <label>Address</label>
                <label>Rating *****</label>
                <label>N50,000 spent</label> on <label>37 completed projects</label>
                
            </div>
            <div class="pull-right">
                Place this at side bar
                <p>Help/Log complain/Sugestion</p>
                <p> Reviews</p>
                <p> Fav Tutors</p>
            </div>
            <div>
                ***** Links*********
                <br />
                @Html.ActionLink("Post New request", "NewRequest", "Tutorials", null, new { @class="btn btn-primary"})
                @Html.ActionLink("View all Posted requests", "Index", "Tutorials", null, new { @class = "btn btn-info" })
            </div>

            <div class="row">
                <h2>Ongoing Tutorials</h2>
            </div>

            <div class="row">
                <h2>Featured tutors</h2>
            </div>
            </div>
        </div>
    </section>*@

            